### PR TITLE
Add package.json

### PR DESCRIPTION
**Pull request by dbkaplun**
Fixes `npm install explosion/displacy`, which doesn't work without a package.json.

### CODE REVIEW

**Comment by ines** [comment]
Thanks! Merged, made some changes and published to npm.

There's now `displacy-demo`, which includes all files in this repo (and Harp as a dependency): https://www.npmjs.com/package/displacy-demo

For just displacy.js, people can now use the `displacy` package: https://www.npmjs.com/package/displacy

**Comment by dbkaplun** [comment]
Thanks @ines! Would you mind sharing how you made the displacy package? I can't find the package.json for it in the Github repo.

**Comment by ines** [comment]
Oh, I actually did this the hacky way and set up a separate package locally. But I should probably fix this and at least add a package.json to the /js folder and put the main.js in .npmignore.

**Comment by dbkaplun** [comment]
I would recommend splitting out the `displacy` package into its own repo (if the displacy and displacy-demo repos will be separate). npm does not support package.json within subdirectories: https://github.com/npm/npm/issues/2974

**Pull request merged**
